### ISSUE TITLE
Question: dataset construction for languages not in the paper

### ISSUE THREAD

**Issue by chapter544** [Babelscape/wikineural#3]
Dear authors,
Could you suggest a script/procedure to construct a span NER dataset for a specific language that is not in the paper, for example, Chinese or Korean?

Regards,

**Comment by sted97** [comment]
Dear @chapter544,

The procedure described in the paper is language-independent, so it can be used to construct a span NER dataset also for Chinese or Korean :)

Kind regards

**Comment by chapter544** [comment]
Hi @sted97 , thank you for your response. Regards!
