### ISSUE TITLE
Entity Classes

### ISSUE THREAD

**Issue by mdconaway** [Babelscape/wikineural#4]
Per the wikineural paper, the classes for this pre-trained model were mapped as such:

> The above classes were converted to the five standard CoNLL-03 NER classes by analyzing how elements belonging to these classes were annotated in the CoNLL dataset. Specifically, we followed the mapping reported below: PERSON → PER, ORG → ORG, GPE → LOC, LOC → LOC, FAC → LOC, PRODUCT → MISC, EVENT → MISC, WORK_OF_ART → MISC, LAW → O, LANGUAGE → MISC, NORP → MISC, DATA → O, TIME → O, PERCENT → O, MONEY → O, QUANTITY → O, ORDINAL → O, CARDINAL → O.

For my purposes I would prefer the classes available before the remapping in the result set, so possible classes of:
```
PERSON, 
ORG, 
GPE,
LOC, 
FAC, 
PRODUCT, 
EVENT, 
WORK_OF_ART, 
LAW, 
LANGUAGE, 
NORP, 
DATA, 
TIME, 
PERCENT, 
MONEY, 
QUANTITY, 
ORDINAL, 
CARDINAL
```
Based on your knowledge of training `wikineural`, what would be the most expedient way to retrain and re-export this model to support the above classes instead of the simplified 4-class scheme?

Thanks!

**Comment by sted97** [comment]
Dear @mdconaway,

This mapping refers to the experiment where we trained a model on OntoNotes and tested it on CoNLL. Therefore, you either need to train a model on OntoNotes, or use a pretrained one like: https://huggingface.co/flair/ner-english-ontonotes

You might also be interested in training a model on MultiNERD, which has a different set of fine-grained classes: https://github.com/Babelscape/multinerd

Hope this helps.

**Comment by mdconaway** [comment]
MultiNERD does look very interesting. Do you plan on releasing a pre trained version at some point? I'd be interested to test MultiNERD if there is a pre-trained version that matches the paper.

Regarding the dataset, it looks like the GitHub page for MultiNERD is missing Chinese language in the data folder.

**Comment by sted97** [comment]
Unfortunately, at the moment, there is no public model pretrained on MultiNERD. However, TNER authors uploaded MultiNERD on HuggingFace (https://huggingface.co/datasets/tner/multinerd) and you could use [this simple notebook](https://github.com/Babelscape/wikineural/blob/master/notebook/WikiNEuRal_HuggingFace.ipynb) to obtain a model equivalent to Babelscape/wikineural-multilingual-ner, but trained on MultiNERD (hence with more NE tags).

Regarding the dataset, thanks for pointing that out, we'll update it as soon as we can.

**Comment by mdconaway** [comment]
Awesome! Thanks! How long do you think it will take to get the Chinese dataset out? I may wait to train up a model until the data is available if you think it will be fairly quick.

**Comment by sted97** [comment]
We cannot find it locally, so it might take a while, sorry for the inconvenience. 
Anyway, since the Chinese language belongs to another linguistic family, perhaps, it would be better to train a separate model for Chinese.

**Comment by sted97** [comment]
Dear @mdconaway, 

We just added the Chinese MultiNERD dataset on the [MultiNERD repository](https://github.com/Babelscape/multinerd), thanks again for pointing it out! We also added the full dataset on HuggingFace [here](https://huggingface.co/datasets/Babelscape/multinerd). We will add the model as well.

Best regards,
